### ISSUE TITLE
Add linting

### ISSUE THREAD

**Issue by aligg** [aligg/Wellness-Wheel#5]
Add eslint

**Comment by jordanchristie** [comment]
Hey, I'm taking on an eslint conversion. What flavor do you think is appropriate?

**Comment by aligg** [comment]
@jordanchristie awesome! I'm totally open - if there is something you're familiar with go for that! otherwise i'm fine with lint rules similar to what airbnb uses - totally flexible I just think it'd be sweet to have something!
